@startuml
actor "run.py" as Runner

participant CLIController
participant SqlAlchemyCompanyRepository

Runner -> CLIController : <<create>>
Runner -> CLIController : start_fly()
CLIController -> CLIController : _statement_service()
CLIController -> SqlAlchemyCompanyRepository : <<create>>

@enduml
